### ISSUE TITLE
Missing preset times when clicking on a notification

### ISSUE THREAD

**Issue by huwan** [dueapp/Due-macOS#223]
When clicking on a notification (>), no preset times are shown. 
 
<img width="350" alt="Jietu20221102-101236" src="https://user-images.githubusercontent.com/1451009/199379194-68f73b85-5072-4e65-9dd0-6a1efc270a93.png">

![Jietu20221102-094931](https://user-images.githubusercontent.com/1451009/199378299-df8193a7-03c3-4ed1-85d2-3feba0817a9b.png)

Other info:
- macOS version: macOS Ventura 13.0 (22A380)
- Due (mac) app version: 22.8 (app store)
- Upgrade Pass ended.

**Comment by junjie** [comment]
Thanks @huwan, we're working on this

**Comment by junjie** [comment]
This bug has been fixed in 22.9, which we're submitting to the App Store for review now.

**Comment by junjie** [comment]
@huwan can you [update to 22.9](https://www.dueapp.com/downloadformac/) from the App Store manually to see if the problem is fixed?

**Comment by huwan** [comment]
It works for me. Thank you!

**Comment by huwan** [comment]
@junjie Hi! This feature is still buggy.

I use iMac with two external displays. The notification only works fine for the main display (iMac). For both external displays, still no preset times displayed.

**Comment by junjie** [comment]
Thanks for reporting this, we'll investigate further

**Comment by junjie** [comment]
@huwan sorry for the delay. can you check if this is fixed?

**Comment by huwan** [comment]
It works fine for me. Thank you.
